# Generated by Django 4.1 on 2022-09-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0006_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signin',
            new_name='signup',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='last_name',
            new_name='lasmaketname',
        ),
    ]
