# Generated by Django 4.1 on 2022-09-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0007_rename_signin_signup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='lasmaketname',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
